theme: jekyll-theme-cayman
title: [Azurilex]
description: [I'm a C/C++ Developer & Reverse Engineer. I developed the well-known exploit for Roblox named Ares back in 2016 (discontinued in 2019). Now, I'm working on Isabelle, the discord bot.]
